server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;

  location /inject.js {
    try_files /inject.js =404;
    add_header Cache-Control "no-store";
  }

  location / {
    try_files $uri $uri/ /index.html;
    add_header Cache-Control "no-store";
  }
}
