# frozen_string_literal: true

source 'https://rubygems.org'

gem 'puma', '~> 6.5'
gem 'rackup', '~> 2.2'
gem 'sequel', '~> 5.86'
gem 'pg', '~> 1.5'
gem 'sinatra', '~> 4.1'
gem 'sinatra-contrib', '~> 4.1'
gem 'faraday', '~> 2.12'
gem 'faraday-multipart', '~> 1.1'
gem 'rack-protection', '~> 4.1'
